### ISSUE TITLE
Development merge

### ISSUE THREAD

**Issue by pdigiglio** [wilhelma/pcvInterpreter#33] opened 2016-09-07 12:58 UTC
@deknapp:
- `operator+=` and `operator-=` shouldn't be member of `StrongTypedef` because not all the types are supposed to be summed or subtracted (i.e. the `ID`'s are not). Please define them for the specific template specialization you need to have these operations only.
- The _rapidjson-prefix_ doesn't belong to the _src_ folder. The _rapidjson_ libraries are now an external project that will be automatically downloaded at build time.
- Again, please pay attention not to commit code that doesn't compile because this will (as it's the case) appear in the _development_ branch history once you merge.

**Comment by deknapp** [comment] 2016-09-07 13:24
I don't see the problem, as if I've clearly tagged the commit as [DOES NOT COMPILE], and the code that was merged was compiling. I need to commit code like this some times - in this case, not locally, because I was having a problem with compilation, and I wanted you to be able to see the code because you wanted to be able to reproduce the problem.

**Comment by deknapp** [comment] 2016-09-07 13:24
The rapidjson-prefix was added in the merge without a conflict, so I didn't consider it. Sorry.

**Comment by deknapp** [comment] 2016-09-07 13:26
I've spent way too much time already dealing with the weird requirements of the StrongTypedef struct. I see no problem as simply defining TIME as a uint_64 in the Types.h file. I had to make a ton of pointless changes just to make it work with the StrongTypedef. Why should I have to have a specific template specialization to add numbers in my code? It's unnecessarily complex!

**Comment by deknapp** [comment] 2016-09-07 13:28
In future merges, I will compress intermediate commits that do not compile, before merging. I have to make these in my own branches, so that I can back up my code.

**Comment by deknapp** [comment] 2016-09-07 13:30
Also @pdigiglio why did you not bring this up earlier, when you added the + and - operators to the StrongTypedef struct? I just changed all the TIME operations in my branch to work with the new operators in StrongTypedef - if the operators hadn't been there, I would have approached this differently.

**Comment by deknapp** [comment] 2016-09-07 13:55
@pdigiglio I squashed the one commit that didn't compile.

**Comment by deknapp** [comment] 2016-09-07 15:16
@pdigiglio I removed rapidjson-prefix.

**Closed as completed** 2016-09-17 18:19 UTC
